# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_youtube_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='youtube_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
